import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const loadingStyles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#1a1a2e',
    zIndex: 1000,
  },
  borderContainer: {
    ...StyleSheet.absoluteFillObject,
  },
  topBorder: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: '#4ECDC4',
    shadowColor: '#4ECDC4',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 10,
  },
  rightBorder: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 3,
    backgroundColor: '#4ECDC4',
    shadowColor: '#4ECDC4',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 10,
  },
  bottomBorder: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: '#4ECDC4',
    shadowColor: '#4ECDC4',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 10,
  },
  leftBorder: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    width: 3,
    backgroundColor: '#4ECDC4',
    shadowColor: '#4ECDC4',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 10,
  },
  lightDot: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#4ECDC4',
    shadowColor: '#4ECDC4',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 20,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 30,
  },
  logoText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#fff',
  },
  logoSubText: {
    fontSize: 24,
    fontWeight: '300',
    color: '#4ECDC4',
    marginTop: -5,
  },
  spinner: {
    marginBottom: 16,
  },
  loadingText: {
    fontSize: 14,
    color: '#888',
  },
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a2e',
  },
  flex: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#2d2d44',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#4ECDC4',
    marginTop: 2,
  },
  periodSelector: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  periodModal: {
    backgroundColor: '#1a1a2e',
    borderRadius: 16,
    width: '85%',
    maxHeight: '60%',
    padding: 0,
    overflow: 'hidden',
  },
  periodModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2d2d44',
  },
  periodModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  periodList: {
    maxHeight: 300,
  },
  periodItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2d2d44',
  },
  periodItemActive: {
    backgroundColor: '#4ECDC4',
  },
  periodItemText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '500',
  },
  periodItemTextActive: {
    color: '#1a1a2e',
  },
  periodItemCount: {
    fontSize: 12,
    color: '#888',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  langButton: {
    backgroundColor: '#4ECDC4',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  langButtonText: {
    color: '#1a1a2e',
    fontWeight: 'bold',
    fontSize: 12,
  },
  importButton: {
    padding: 6,
    backgroundColor: '#2d2d44',
    borderRadius: 8,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 200,
  },
  filterSection: {
    marginBottom: 16,
  },
  filterLabel: {
    fontSize: 14,
    color: '#fff',
    marginBottom: 10,
    fontWeight: '600',
  },
  filterScroll: {
    marginHorizontal: -16,
  },
  filterRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 8,
  },
  filterChip: {
    backgroundColor: '#2d2d44',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 20,
    minWidth: 60,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  filterChipActive: {
    backgroundColor: '#4ECDC4',
    borderColor: '#4ECDC4',
  },
  filterChipText: {
    color: '#aaa',
    fontSize: 15,
    fontWeight: '600',
  },
  filterChipTextActive: {
    color: '#1a1a2e',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 12,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
  },
  loadingText: {
    color: '#888',
    marginLeft: 8,
  },
  noDataText: {
    color: '#888',
    fontStyle: 'italic',
    padding: 16,
  },
  programsScroll: {
    marginHorizontal: -16,
    paddingHorizontal: 16,
  },
  programCard: {
    backgroundColor: '#2d2d44',
    borderRadius: 12,
    padding: 12,
    marginRight: 10,
    minWidth: 160,
    maxWidth: 180,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  programCardSelected: {
    borderColor: '#4ECDC4',
    backgroundColor: '#3d3d54',
  },
  programHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  programBrand: {
    fontSize: 11,
    color: '#4ECDC4',
    fontWeight: '600',
  },
  programYear: {
    fontSize: 11,
    color: '#888',
    fontWeight: '500',
  },
  programModel: {
    fontSize: 14,
    color: '#fff',
    fontWeight: 'bold',
    marginTop: 4,
  },
  programTrim: {
    fontSize: 10,
    color: '#aaa',
    marginTop: 2,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 8,
  },
  cashBadge: {
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  cashBadgeText: {
    fontSize: 9,
    color: '#fff',
    fontWeight: 'bold',
  },
  bonusBadge: {
    backgroundColor: '#FFD700',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  bonusBadgeText: {
    fontSize: 9,
    color: '#1a1a2e',
    fontWeight: 'bold',
  },
  option2Badge: {
    backgroundColor: '#4ECDC4',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    marginTop: 4,
    alignSelf: 'flex-start',
  },
  option2BadgeText: {
    fontSize: 9,
    color: '#1a1a2e',
    fontWeight: 'bold',
  },
  selectedInfo: {
    backgroundColor: '#2d2d44',
    borderRadius: 12,
    padding: 14,
    marginTop: 12,
  },
  selectedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  selectedTitleContainer: {
    flex: 1,
    marginRight: 10,
  },
  selectedBrand: {
    fontSize: 12,
    color: '#4ECDC4',
    fontWeight: '600',
  },
  selectedTitle: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
    marginTop: 2,
  },
  selectedTrim: {
    fontSize: 12,
    color: '#aaa',
    marginTop: 2,
  },
  optionsPreview: {
    flexDirection: 'row',
    marginTop: 12,
    gap: 10,
  },
  optionPreview: {
    flex: 1,
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    padding: 10,
  },
  optionPreviewDisabled: {
    opacity: 0.5,
  },
  optionPreviewLabel: {
    fontSize: 11,
    color: '#888',
  },
  optionPreviewValue: {
    fontSize: 13,
    color: '#fff',
    fontWeight: '600',
    marginTop: 4,
  },
  optionPreviewValueNA: {
    fontSize: 13,
    color: '#666',
    fontWeight: '600',
    marginTop: 4,
  },
  optionPreviewNote: {
    fontSize: 9,
    color: '#666',
    marginTop: 2,
  },
  bonusCashInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#3d3d54',
    gap: 6,
  },
  bonusCashText: {
    fontSize: 12,
    color: '#FFD700',
    fontWeight: '500',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2d2d44',
    borderRadius: 12,
    paddingHorizontal: 16,
  },
  currencySymbol: {
    fontSize: 22,
    color: '#4ECDC4',
    fontWeight: 'bold',
  },
  priceInput: {
    flex: 1,
    fontSize: 22,
    color: '#fff',
    paddingVertical: 14,
    paddingHorizontal: 8,
  },
  calculateButton: {
    backgroundColor: '#4ECDC4',
    borderRadius: 12,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    gap: 8,
  },
  calculateButtonDisabled: {
    opacity: 0.5,
  },
  calculateButtonText: {
    color: '#1a1a2e',
    fontSize: 16,
    fontWeight: 'bold',
  },
  resultsSummary: {
    backgroundColor: '#2d2d44',
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    alignItems: 'center',
  },
  summaryTitle: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
    textAlign: 'center',
  },
  summaryPrice: {
    fontSize: 24,
    color: '#4ECDC4',
    fontWeight: 'bold',
    marginTop: 4,
  },
  summaryDetails: {
    marginTop: 8,
  },
  summaryCash: {
    fontSize: 12,
    color: '#FF6B6B',
    textAlign: 'center',
  },
  summaryBonus: {
    fontSize: 12,
    color: '#FFD700',
    textAlign: 'center',
    marginTop: 2,
  },
  legend: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
    marginBottom: 12,
    paddingVertical: 8,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  legendText: {
    fontSize: 11,
    color: '#888',
  },
  resultCard: {
    backgroundColor: '#2d2d44',
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
  },
  resultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  resultTerm: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  bestBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  bestBadgeOption1: {
    backgroundColor: '#FF6B6B',
  },
  bestBadgeOption2: {
    backgroundColor: '#4ECDC4',
  },
  bestBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#1a1a2e',
  },
  optionsGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  optionCard: {
    flex: 1,
    borderRadius: 8,
    padding: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  optionCard1: {
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
  },
  optionCard2: {
    backgroundColor: 'rgba(78, 205, 196, 0.1)',
  },
  optionCardBest: {
    borderColor: '#4ECDC4',
  },
  optionCardTitle: {
    fontSize: 12,
    color: '#888',
    fontWeight: '600',
    marginBottom: 8,
  },
  optionDetail: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  optionDetailLabel: {
    fontSize: 11,
    color: '#888',
  },
  optionDetailValue: {
    fontSize: 11,
    color: '#fff',
    fontWeight: '500',
  },
  optionMonthly: {
    fontSize: 13,
    color: '#4ECDC4',
    fontWeight: 'bold',
  },
  noOption: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  noOptionText: {
    fontSize: 14,
    color: '#666',
    fontStyle: 'italic',
  },
  savingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#3d3d54',
    gap: 6,
  },
  savingsText: {
    fontSize: 13,
    color: '#4ECDC4',
    fontWeight: '600',
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#2d2d44',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 8,
  },
  modalSubtitle: {
    fontSize: 14,
    color: '#888',
    textAlign: 'center',
    marginBottom: 20,
  },
  passwordInput: {
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    color: '#fff',
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  modalButtonCancel: {
    flex: 1,
    backgroundColor: '#3d3d54',
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
  },
  modalButtonCancelText: {
    color: '#aaa',
    fontSize: 16,
    fontWeight: '600',
  },
  modalButtonConfirm: {
    flex: 1,
    backgroundColor: '#4ECDC4',
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
  },
  modalButtonConfirmText: {
    color: '#1a1a2e',
    fontSize: 16,
    fontWeight: '600',
  },
  // Rates table styles
  ratesTable: {
    marginTop: 12,
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    overflow: 'hidden',
  },
  ratesHeader: {
    flexDirection: 'row',
    backgroundColor: '#3d3d54',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  ratesHeaderCell: {
    flex: 1,
    fontSize: 11,
    color: '#aaa',
    fontWeight: '600',
    textAlign: 'center',
  },
  ratesRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#2d2d44',
  },
  ratesRowSelected: {
    backgroundColor: '#4ECDC4',
  },
  ratesCell: {
    flex: 1,
    fontSize: 13,
    color: '#fff',
    textAlign: 'center',
  },
  ratesCellSelected: {
    color: '#1a1a2e',
    fontWeight: 'bold',
  },
  ratesCellOption1: {
    color: '#FF6B6B',
  },
  ratesCellOption2: {
    color: '#4ECDC4',
  },
  rebatesSummary: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#3d3d54',
    gap: 6,
  },
  rebateItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  rebateLabel: {
    fontSize: 12,
    color: '#FF6B6B',
  },
  rebateValue: {
    fontSize: 12,
    color: '#FF6B6B',
    fontWeight: 'bold',
  },
  rebateLabelBonus: {
    fontSize: 12,
    color: '#FFD700',
  },
  rebateValueBonus: {
    fontSize: 12,
    color: '#FFD700',
    fontWeight: 'bold',
  },
  // Input styles
  inputRow: {
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 13,
    color: '#aaa',
    marginBottom: 6,
  },
  // Term selection styles
  termSection: {
    marginTop: 8,
  },
  termButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  termButton: {
    backgroundColor: '#2d2d44',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    minWidth: 90,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  termButtonActive: {
    backgroundColor: '#4ECDC4',
    borderColor: '#4ECDC4',
  },
  termButtonText: {
    fontSize: 14,
    color: '#aaa',
    fontWeight: '600',
  },
  termButtonTextActive: {
    color: '#1a1a2e',
  },
  // Fees section styles
  feesSection: {
    marginTop: 16,
    backgroundColor: '#2d2d44',
    borderRadius: 12,
    padding: 12,
  },
  feesSectionTitle: {
    fontSize: 13,
    color: '#aaa',
    fontWeight: '600',
    marginBottom: 10,
  },
  feesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  feeField: {
    flex: 1,
    minWidth: 100,
  },
  feeLabel: {
    fontSize: 11,
    color: '#888',
    marginBottom: 4,
  },
  feeInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  feeSymbol: {
    fontSize: 14,
    color: '#4ECDC4',
    fontWeight: '600',
  },
  feeInput: {
    flex: 1,
    fontSize: 14,
    color: '#fff',
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  feeNote: {
    fontSize: 9,
    color: '#666',
    marginTop: 2,
  },
  exchangeRow: {
    flexDirection: 'row',
    gap: 12,
  },
  exchangeField: {
    flex: 1,
  },
  // Frequency buttons
  frequencyButtons: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  frequencyButton: {
    flex: 1,
    backgroundColor: '#2d2d44',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  frequencyButtonActive: {
    backgroundColor: '#FFD700',
    borderColor: '#FFD700',
  },
  frequencyButtonText: {
    fontSize: 13,
    color: '#aaa',
    fontWeight: '600',
  },
  frequencyButtonTextActive: {
    color: '#1a1a2e',
  },
  // Option selection buttons
  optionButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  optionButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'transparent',
  },
  optionButton1: {
    backgroundColor: 'rgba(255, 107, 107, 0.2)',
    borderColor: 'rgba(255, 107, 107, 0.3)',
  },
  optionButton2: {
    backgroundColor: 'rgba(78, 205, 196, 0.2)',
    borderColor: 'rgba(78, 205, 196, 0.3)',
  },
  optionButtonActive1: {
    backgroundColor: '#FF6B6B',
    borderColor: '#FF6B6B',
  },
  optionButtonActive2: {
    backgroundColor: '#4ECDC4',
    borderColor: '#4ECDC4',
  },
  optionButtonDisabled: {
    backgroundColor: 'rgba(100, 100, 100, 0.2)',
    opacity: 0.5,
  },
  optionButtonText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
  },
  optionButtonTextActive: {
    color: '#1a1a2e',
  },
  optionButtonTextDisabled: {
    fontSize: 14,
    color: '#666',
  },
  optionButtonSubtext: {
    fontSize: 12,
    color: '#aaa',
    marginTop: 4,
  },
  // Best option banner
  bestOptionBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 10,
    marginBottom: 12,
    gap: 8,
  },
  bestOptionBanner1: {
    backgroundColor: '#FF6B6B',
  },
  bestOptionBanner2: {
    backgroundColor: '#4ECDC4',
  },
  bestOptionText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1a1a2e',
  },
  bestOptionSavings: {
    fontSize: 12,
    color: '#1a1a2e',
    fontWeight: '600',
  },
  // Option card enhancements
  optionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  optionSubtitle: {
    fontSize: 10,
    color: '#888',
    marginBottom: 10,
  },
  optionRateValue: {
    fontSize: 14,
    color: '#4ECDC4',
    fontWeight: 'bold',
  },
  optionMainResult: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderRadius: 8,
    padding: 10,
    marginVertical: 8,
    alignItems: 'center',
  },
  optionMonthlyLabel: {
    fontSize: 10,
    color: '#aaa',
  },
  optionMonthlyValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#4ECDC4',
  },
  optionTotalValue: {
    fontSize: 13,
    color: '#fff',
    fontWeight: 'bold',
  },
  noOptionSubtext: {
    fontSize: 11,
    color: '#555',
    marginTop: 4,
  },
  // Bonus cash note
  bonusCashNote: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    padding: 12,
    borderRadius: 8,
    marginTop: 12,
    gap: 8,
  },
  bonusCashNoteText: {
    fontSize: 12,
    color: '#FFD700',
    flex: 1,
  },
  // Email button and modal styles
  sendEmailButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4ECDC4',
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    gap: 8,
  },
  sendEmailButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  // Share actions row (SMS + Print)
  shareActionsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  shareSmsButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#5C6BC0',
    borderRadius: 10,
    padding: 14,
    gap: 6,
  },
  printButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#78909C',
    borderRadius: 10,
    padding: 14,
    gap: 6,
  },
  exportExcelButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#217346',
    borderRadius: 10,
    padding: 14,
    gap: 6,
  },
  shareButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  // SMS Preview Modal styles
  smsPreviewModalContent: {
    backgroundColor: '#1a1a2e',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 30,
    maxHeight: '85%',
  },
  smsPreviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 20,
    paddingBottom: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#2d2d44',
  },
  smsPreviewIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(78, 205, 196, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  smsPreviewTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  smsPreviewClose: {
    padding: 8,
  },
  smsPreviewBody: {
    padding: 20,
  },
  smsPreviewLabel: {
    fontSize: 14,
    color: '#888',
    marginBottom: 12,
  },
  smsPreviewTextInput: {
    backgroundColor: '#2d2d44',
    borderRadius: 12,
    padding: 16,
    fontSize: 14,
    color: '#fff',
    minHeight: 200,
    maxHeight: 300,
    textAlignVertical: 'top',
  },
  smsPreviewCharCount: {
    fontSize: 12,
    color: '#666',
    textAlign: 'right',
    marginTop: 8,
  },
  smsPreviewButtons: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    gap: 12,
  },
  smsPreviewCancelButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#2d2d44',
    alignItems: 'center',
  },
  smsPreviewCancelText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#888',
  },
  smsPreviewSendButton: {
    flex: 1,
    flexDirection: 'row',
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#5C6BC0',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  smsPreviewSendText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  emailModalContent: {
    backgroundColor: '#1a1a2e',
    borderRadius: 16,
    width: '100%',
    maxWidth: 420,
    maxHeight: '60%',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  emailModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2d2d44',
    flexShrink: 0,
  },
  emailModalIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(78, 205, 196, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  emailModalTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#fff',
    flex: 1,
  },
  emailModalClose: {
    padding: 6,
  },
  emailModalBody: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  emailModalLabel: {
    fontSize: 13,
    color: '#888',
    marginBottom: 5,
    marginTop: 8,
  },
  emailModalInput: {
    backgroundColor: '#2d2d44',
    borderRadius: 10,
    padding: 12,
    fontSize: 15,
    color: '#fff',
  },
  emailPreviewBox: {
    backgroundColor: '#2d2d44',
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
    alignItems: 'center',
  },
  emailPreviewTitle: {
    fontSize: 11,
    color: '#888',
    marginBottom: 4,
  },
  emailPreviewText: {
    fontSize: 13,
    color: '#fff',
    marginBottom: 2,
  },
  emailPreviewPayment: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#4ECDC4',
    marginTop: 4,
  },
  emailModalButtons: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
    flexShrink: 0,
    borderTopWidth: 1,
    borderTopColor: '#2d2d44',
  },
  emailModalCancelButton: {
    flex: 1,
    backgroundColor: '#2d2d44',
    borderRadius: 10,
    padding: 12,
    alignItems: 'center',
  },
  emailModalCancelText: {
    fontSize: 16,
    color: '#fff',
  },
  emailModalSendButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#4ECDC4',
    borderRadius: 10,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  emailModalSendButtonDisabled: {
    opacity: 0.6,
  },
  emailModalSendText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1a2e',
  },
  // Inventory styles
  inventorySubtitle: {
    fontSize: 13,
    color: '#888',
    marginBottom: 12,
  },
  inventoryScroll: {
    marginHorizontal: -8,
  },
  inventoryCard: {
    backgroundColor: '#2d2d44',
    borderRadius: 12,
    padding: 14,
    marginHorizontal: 6,
    minWidth: 160,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  inventoryCardSelected: {
    borderColor: '#4ECDC4',
    backgroundColor: '#3d3d54',
  },
  inventoryStock: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#4ECDC4',
    marginBottom: 4,
  },
  inventoryModel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
  },
  inventoryTrim: {
    fontSize: 12,
    color: '#888',
    marginBottom: 4,
  },
  inventoryVin: {
    fontSize: 10,
    color: '#4ECDC4',
    fontFamily: 'monospace',
    marginBottom: 6,
  },
  inventoryPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFB347',
  },
  inventoryProfit: {
    fontSize: 11,
    color: '#4ECDC4',
    marginTop: 4,
  },
  noInventoryText: {
    color: '#888',
    fontStyle: 'italic',
    padding: 16,
    textAlign: 'center',
  },
  noInventoryContainer: {
    padding: 12,
  },
  manualVinContainer: {
    marginTop: 12,
    backgroundColor: '#1e1e2e',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#333',
  },
  manualVinLabel: {
    color: '#4ECDC4',
    fontSize: 13,
    marginBottom: 8,
    fontWeight: '500',
  },
  manualVinInput: {
    backgroundColor: '#2d2d44',
    borderRadius: 8,
    padding: 12,
    color: '#fff',
    fontSize: 15,
    fontFamily: 'monospace',
    borderWidth: 1,
    borderColor: '#444',
  },
  manualVinError: {
    color: '#ff6b6b',
    fontSize: 11,
    marginTop: 6,
  },
  manualVinSuccess: {
    color: '#4ECDC4',
    fontSize: 12,
    marginTop: 6,
    fontWeight: '500',
  },
  selectedInventoryBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(78, 205, 196, 0.1)',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#4ECDC4',
  },
  selectedInventoryInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  selectedInventoryText: {
    fontSize: 13,
    color: '#4ECDC4',
    flex: 1,
  },
  selectedInventoryVin: {
    fontSize: 11,
    color: '#888',
    fontFamily: 'monospace',
    marginLeft: 28,
    marginTop: 2,
  },
  // Styles Auto-financing banner
  autoFinancingBanner: {
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#FFD700',
  },
  autoFinancingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  autoFinancingTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFD700',
  },
  autoFinancingContent: {
    gap: 4,
  },
  autoFinancingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  autoFinancingLabel: {
    fontSize: 13,
    color: '#aaa',
  },
  autoFinancingLabelTotal: {
    fontSize: 13,
    color: '#fff',
    fontWeight: 'bold',
  },
  autoFinancingValue: {
    fontSize: 14,
    color: '#4ECDC4',
    fontWeight: 'bold',
  },
  autoFinancingValueBonus: {
    fontSize: 14,
    color: '#9b59b6',
    fontWeight: 'bold',
  },
  autoFinancingValueTotal: {
    fontSize: 15,
    color: '#FFD700',
    fontWeight: 'bold',
  },
  autoFinancingValueRate: {
    fontSize: 13,
    color: '#4CAF50',
    fontStyle: 'italic',
  },
  autoFinancingSource: {
    fontSize: 10,
    color: '#666',
    marginTop: 6,
    fontStyle: 'italic',
  },
  // Styles Accessoires
  accessoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  accessoryDescInput: {
    flex: 2,
    backgroundColor: '#2a2a3e',
    borderColor: '#4CAF50',
    color: '#ffffff',
    fontSize: 16,
  },
  accessoryPriceInput: {
    flex: 1,
    textAlign: 'right',
    backgroundColor: '#2a2a3e',
    borderColor: '#4CAF50',
    color: '#ffffff',
    fontSize: 16,
  },
  removeAccessoryBtn: {
    padding: 4,
  },
  addAccessoryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#4CAF50',
    borderStyle: 'dashed',
    gap: 6,
  },
  addAccessoryText: {
    color: '#4CAF50',
    fontSize: 14,
    fontWeight: '600',
  },
  accessoriesTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#333',
  },
  accessoriesTotalLabel: {
    color: '#aaa',
    fontSize: 14,
  },
  accessoriesTotalValue: {
    color: '#4CAF50',
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Base input style for accessories
  input: {
    backgroundColor: '#2d2d44',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#444',
    color: '#ffffff',
    fontSize: 15,
  },
  // Section header for accessories
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  // ============ LEASE SCI STYLES ============
  leaseToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#4ECDC4',
    backgroundColor: 'transparent',
  },
  leaseToggleActive: {
    backgroundColor: '#4ECDC4',
    borderColor: '#4ECDC4',
  },
  leaseToggleText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#4ECDC4',
  },
  leaseToggleTextActive: {
    color: '#fff',
  },
  leaseContent: {
    marginTop: 12,
    gap: 12,
  },
  leaseInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  leaseInputLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ccc',
    minWidth: 100,
  },
  leaseInput: {
    flex: 1,
    backgroundColor: '#2d2d44',
    borderRadius: 8,
    padding: 10,
    color: '#fff',
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#3d3d5c',
  },
  leaseInputHint: {
    fontSize: 11,
    color: '#888',
    minWidth: 55,
  },
  // Residual by km table
  residualKmTable: {
    backgroundColor: '#1e2a3a',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#2d3d54',
  },
  residualKmTitle: {
    fontSize: 12,
    color: '#8899aa',
    fontWeight: '600',
    marginBottom: 8,
    textTransform: 'uppercase' as any,
    letterSpacing: 0.5,
  },
  residualKmRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
    marginBottom: 2,
  },
  residualKmRowSelected: {
    backgroundColor: 'rgba(78, 205, 196, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(78, 205, 196, 0.3)',
  },
  residualKmHeader: {
    flex: 1,
    alignItems: 'center' as any,
  },
  residualKmHeaderText: {
    fontSize: 10,
    color: '#556677',
    fontWeight: '700',
    textTransform: 'uppercase' as any,
  },
  residualKmCell: {
    flex: 1,
    alignItems: 'center' as any,
  },
  residualKmText: {
    fontSize: 13,
    color: '#aabbcc',
    fontWeight: '500',
  },
  residualKmTextSelected: {
    color: '#4ECDC4',
    fontWeight: '700',
  },
  residualKmValue: {
    fontSize: 13,
    color: '#aabbcc',
    fontWeight: '500',
  },
  residualKmValueSelected: {
    color: '#4ECDC4',
    fontWeight: '700',
  },
  leaseInfoBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1e2a3a',
    borderRadius: 8,
    padding: 8,
    borderWidth: 1,
    borderColor: '#2d4a6c',
  },
  leaseInfoText: {
    fontSize: 11,
    color: '#88aabb',
    flex: 1,
  },
  leaseWarningBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#3a1e1e',
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: '#6c2d2d',
  },
  leaseWarningText: {
    fontSize: 11,
    color: '#FF6B6B',
    flex: 1,
  },
  leaseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  leaseLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ccc',
    minWidth: 100,
  },
  leaseKmButtons: {
    flexDirection: 'row',
    gap: 6,
  },
  leaseKmBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#2d2d44',
    borderWidth: 1,
    borderColor: '#3d3d5c',
  },
  leaseKmBtnActive: {
    backgroundColor: '#4ECDC4',
    borderColor: '#4ECDC4',
  },
  leaseKmBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#aaa',
  },
  leaseKmBtnTextActive: {
    color: '#1a1a2e',
  },
  leaseTermScroll: {
    flexGrow: 0,
  },
  leaseTermBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#2d2d44',
    marginRight: 6,
    borderWidth: 1,
    borderColor: '#3d3d5c',
  },
  leaseTermBtnActive: {
    backgroundColor: '#4ECDC4',
    borderColor: '#4ECDC4',
  },
  leaseTermBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#aaa',
  },
  leaseTermBtnTextActive: {
    color: '#1a1a2e',
  },
  leaseResults: {
    gap: 10,
  },
  leaseResidualInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#2d2d44',
    borderRadius: 10,
    padding: 12,
  },
  leaseResidualLabel: {
    fontSize: 13,
    color: '#aaa',
    fontWeight: '500',
  },
  leaseResidualValue: {
    fontSize: 15,
    color: '#4ECDC4',
    fontWeight: '700',
  },
  leaseBestBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFD700',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  leaseBestText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1a1a2e',
    flex: 1,
  },
  leaseBestSavings: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1a1a2e',
  },
  leaseCardsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  leaseCard: {
    flex: 1,
    backgroundColor: '#2d2d44',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#3d3d5c',
    gap: 6,
  },
  leaseCardAlt: {
    backgroundColor: '#1e2a3a',
    borderColor: '#2d4a6c',
  },
  leaseCardBest: {
    borderColor: '#4ECDC4',
    borderWidth: 2,
  },
  leaseCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  leaseCardTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fff',
    flex: 1,
  },
  leaseCardDetail: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  leaseCardDetailLabel: {
    fontSize: 11,
    color: '#888',
  },
  leaseCardDetailValue: {
    fontSize: 11,
    color: '#ccc',
    fontWeight: '500',
  },
  leaseCardRateValue: {
    fontSize: 13,
    color: '#4ECDC4',
    fontWeight: '700',
  },
  leaseCardMainResult: {
    alignItems: 'center',
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    padding: 10,
    marginVertical: 4,
  },
  leaseCardPaymentLabel: {
    fontSize: 10,
    color: '#888',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  leaseCardPaymentValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#4ECDC4',
    marginTop: 2,
  },
  leaseCardTaxDetail: {
    fontSize: 10,
    color: '#777',
    marginTop: 2,
  },
  leaseCardTaxBreakdown: {
    marginTop: 3,
    paddingTop: 3,
    borderTopWidth: 1,
    borderTopColor: '#333',
  },
  leaseCardTaxLine: {
    fontSize: 9,
    color: '#666',
    lineHeight: 14,
  },
  leaseCardRabaisLine: {
    fontSize: 9,
    color: '#4ECDC4',
    marginTop: 2,
    fontWeight: '500',
  },
  bestLeaseBox: {
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#FFD700',
    padding: 12,
    marginTop: 12,
    marginBottom: 8,
  },
  bestLeaseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 8,
  },
  bestLeaseTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFD700',
    letterSpacing: 1,
  },
  bestLeaseContent: {
    gap: 4,
  },
  bestLeaseRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bestLeaseLabel: {
    fontSize: 11,
    color: '#999',
  },
  bestLeaseValue: {
    fontSize: 11,
    color: '#fff',
    fontWeight: '600',
  },
  bestLeaseTap: {
    fontSize: 9,
    color: '#666',
    textAlign: 'center',
    marginTop: 6,
    fontStyle: 'italic',
  },
  analysisSection: {
    marginTop: 12,
    marginBottom: 4,
  },
  analysisSectionTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#4ECDC4',
    letterSpacing: 1,
    textAlign: 'center',
    marginBottom: 8,
  },
  analysisKmBlock: {
    marginBottom: 10,
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    padding: 8,
  },
  analysisKmTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ccc',
    marginBottom: 6,
    textAlign: 'center',
  },
  analysisHeaderRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#333',
    paddingBottom: 4,
    marginBottom: 2,
  },
  analysisDataRow: {
    flexDirection: 'row',
    paddingVertical: 3,
    borderBottomWidth: 0.5,
    borderBottomColor: '#222',
  },
  analysisBestRow: {
    backgroundColor: 'rgba(255, 215, 0, 0.15)',
    borderRadius: 4,
  },
  analysisCell: {
    fontSize: 10,
    color: '#aaa',
    textAlign: 'center',
  },
  analysisCellHeader: {
    fontWeight: '700',
    color: '#888',
    fontSize: 9,
    textTransform: 'uppercase',
  },
  leaseCardTotalValue: {
    fontSize: 12,
    color: '#4ECDC4',
    fontWeight: '600',
  },
  leaseNoOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 14,
    backgroundColor: '#2d2d44',
    borderRadius: 10,
  },
  leaseNoOptionText: {
    fontSize: 13,
    color: '#888',
    flex: 1,
  },
  leaseVsFinance: {
    backgroundColor: '#1e1e3a',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#3d3d5c',
  },
  leaseVsFinanceTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFD700',
    textAlign: 'center',
    marginBottom: 10,
  },
  leaseVsFinanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  leaseVsFinanceCol: {
    flex: 1,
    alignItems: 'center',
  },
  leaseVsFinanceLabel: {
    fontSize: 11,
    color: '#888',
    marginBottom: 4,
  },
  leaseVsFinanceValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#4ECDC4',
  },
  leaseVsFinanceSub: {
    fontSize: 10,
    color: '#666',
    marginTop: 2,
  },
  leaseVsFinanceDivider: {
    width: 1,
    height: 50,
    backgroundColor: '#3d3d5c',
    marginHorizontal: 8,
  },
});
// Last update: Thu Feb 19 19:47:53 UTC 2026
